- package.json
- yarn.lock
The superagent package is imported and used directly in the WebhookNotificationActivity so is better to add it to package.json.
> Add superagent as dependency

- CreateNotificationActivity/handler.ts
- package.json
- yarn.lock
Reverts teamdigitale/io-functions-services#26
> Revert "[#169703944] Disable email channel if profile email is not validated"

- CreateMessage/handler.ts
- CreateMessage/index.ts
- EmailNotificationActivity/index.ts
- package.json
- yarn.lock
Need to fix the missing `initAppInsights` in the latest `io-functions-commons`
> [#172220283] Use commons agent for MailUP calls

- CreateMessage/index.ts
- utils/appinsights.ts
let dev configure samling and enable/disable application insights from environment variables
> [ #172488185] make application insights configurable from env

- CreateNotificationActivity/handler.ts
- CreateNotificationActivity/index.ts
remove sender services cache since is is not used anywhere
> [#172768595] remove sender services

- package.json
- yarn.lock
> [#174315757] Update io-functions-commons to v13

- CreateService/handler.ts
- GetService/handler.ts
- GetUserServices/handler.ts
- RegenerateServiceKey/handler.ts
- UpdateService/handler.ts
- UploadServiceLogo/handler.ts
- utils/api.ts
This PR includes a new utility function withApiRequestWrapper that allows to wrap API calls and generalize a common pattern described here.
> [#174902061] Add wrapper on api call tasks

- CreateMessage/index.ts
- CreateNotificationActivity/index.ts
- CreateService/index.ts
- EmailNotificationActivity/index.ts
- GetMessage/index.ts
- GetSubscriptionsFeed/index.ts
- StoreMessageContentActivity/index.ts
- clients/admin.ts
- utils/__tests__/config.test.ts
- utils/config.ts
- utils/cosmosdb.ts
This PR introduces the utils/config module which aims to be the unique interface for application configuration.
Every place in which the application used to directly access env variable has been refactored to use this module instead.
> [#175119553] Centralize environment variables in a single config module

- azure-templates/deploy-steps.yml
> Change deploy slot from production to staging

- .devops/azure-templates/setup-project.yml
- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- package.json
Add:
* use a setup template 
* fix hit cache variable
* update template version
> [#175476527] Refactor pipeline

- package.json
- yarn.lock
Upgrade from `italia-utils` to `@pagopa/openapi-codegen-ts`
> Upgrate to @pagopa/openapi-codegen-ts

- extensions.csproj
- host.json
This is required in order to mitigate bug release on current version of Azure Functions runtime.
> Mitigation for the Azure Durable Functions extension error

- CreatedMessageOrchestrator/index.ts
- CreatedMessageOrchestrator/utils.ts
This will enable us to query logs for all message sent by a given Service.
> [#IPV-74] Add `serviceId` to message creation tracking

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- Upgrade azure devops templates to v17
- New healthcheck management
Fix healthcheck
> [IP-416] Fix healthcheck stage

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
> [#IP-456] Upgrade pipelines template to v18

- CreateMessage/handler.ts
`serviceCategory` is `STANDARD` when service metadata is undefined.
not tested
> [#IC-132] Fix runtime error for undefined service metadata

- openapi/index.yaml
- openapi/index.yaml.template
The SubscriptionFeed documentation was updated.
More focus on how the subfeed should be used inside the openapi docs.
not needed
> [#IC-141] Update subfeed docs in openapi files

- GetLimitedProfileByPOST/handler.ts
- GetServiceActivation/__tests__/handler.test.ts
- GetServiceActivation/function.json
- GetServiceActivation/handler.ts
- GetServiceActivation/index.ts
- UpsertServiceActivation/__tests__/handler.test.ts
- UpsertServiceActivation/function.json
- UpsertServiceActivation/handler.ts
- UpsertServiceActivation/index.ts
- __mocks__/mocks.ts
- openapi/index.yaml
- openapi/index.yaml.template
- package.json
- utils/__tests__/profile.test.ts
- utils/logging.ts
- utils/profile.ts
- utils/services.ts
- yarn.lock
Create a set of API to interact with user `Activation`.
`POST /api/v1/activations` to retrieve an activation for a user (the fiscal code is provided into the payload)
`PUT /api/v1/activations` to upsert an activation for a user
A `SPECIAL` service need APIs to read and update the user's Activation. Activation is evaluated to check if a Service can send messages to a User.
unit tests
> [#IC-52] Activation handling API for Special Services

- ProcessMessage/handler.ts
I added a `trackEvent` in `ProcessMessage` function that tracks the `PROCESSED` message status with also the time elapsed since the message has been created.
This change allows us to track the time elapsed from creation to processing of the message. This is an important metric to evaluate when developing new functionality on IO.
**This change has NOT been tested** as I am unable to setup the local environment. Please help me test this change!
> track "processed" status

- GetMessage/__tests__/handler.test.ts
- Info/__tests__/handler.test.ts
- Info/handler.ts
- ProcessMessage/__tests__/handler.test.ts
- package.json
- yarn.lock
Update fn-commons to new major version and fix breaking changes.
Update io-fn-commons lib
Fix healthcheck breaking changes
Fix message_status breaking changes
Required to continue to use future feature released on fn-commons
unit test
> [#IC-349] Update io-functions-commons lib to 23.1.0

- openapi/index.yaml
- openapi/index.yaml.template
update open api hostname (from api.io.italia.it to api.io.pagopa.it)
Change hostname according to PagoPA fqdn standards.
> Update hostname in api-spec

- ProcessMessage/__tests__/handler.test.ts
- ProcessMessage/handler.ts
- throw an Error if message-status update fails while storing PROCESSED or REJECTED status
lack of message-status  related to non pending messages is causing inbox failures
Unit test
> [#IC-493] [FIX] Throw error if message-status update fails

- openapi/index.yaml
- package.json
- yarn.lock
- Update fn-commons in order to fix ThirdPartyData decoder
> [#ICC-98] Update fn-commons

- .devops/code-review-pipelines.yml
- GetMessage/__tests__/handler.test.ts
- GetMessage/handler.ts
- GetMessage/index.ts
- __integrations__/environments/env.io-functions-services
- __mocks__/mocks.ts
- clients/payment-updater.ts
- openapi/payment-updater.yaml
- package.json
- utils/config.ts
- utils/responses.ts
- yarn.lock
Add message status as boolean to message details returned to Organizations. This info will be retrieved directly from payment-updater.
add payment status to message details
add payment updater call
The Organization subscribed to premium services could retrieved payment status for advanced messages.
unit tests
> [#ICC-103] Add payment-status from payment-updater to message details

- ProcessMessage/handler.ts
It is necessary to track if a message is thirdParty
This is needed in order to build up monitoring dashboards
unit test
> [#ICC-119] - Add ThirdPartyData event tracking flag

- __integrations__/index.test.ts
- package.json
- yarn.lock
Update the fn-commons libs to import the fix on the message model: now will proper retrieve a message without content if the blob is missing.
update fn-commons libs
add IT for getMessage without content
The Service calling the getMessage when the message is in status ACCEPTED, will never retrieve the message becouse the getBlobContent will fail.
integration test
> [#ICC-167] Update fn-commons and add IT for get message withouth content

- CreateMessage/__tests__/handler.test.ts
- CreateMessage/handler.ts
- __integrations__/index.test.ts
- package.json
- utils/__tests__/middlewares.test.ts
- utils/message_middlewares.ts
- utils/responses.ts
- yarn.lock
* Updated `ts-commons` to `10.10.0`
* Added `ResponseErrorSimplifiedFromValidationErrors` function in `responses.ts` in order to send more readable validation errors
* Modified `MessagePayloadMiddleware` in order to use the new `ResponseErrorSimplifiedFromValidationErrors`
* Modified the `CreateMessageHandler` in order to send a more readable validation error in case of bad created message event
* Added unit test
I have applied those changes in order to send more readable validation errors when something goes wrong during the `CreateMessage`.
> [ICC-226] More readable errors

- GetMessage/__tests__/handler.test.ts
- GetMessage/handler.ts
- OnFailedProcessMessage/__tests__/handler.test.ts
- OnFailedProcessMessage/handler.ts
- ProcessMessage/__tests__/handler.test.ts
- ProcessMessage/handler.ts
- __integrations__/index.test.ts
- __integrations__/package.json
- __integrations__/yarn.lock
- __mocks__/mocks.ts
- openapi/index.yaml
- openapi/index.yaml.template
- package.json
- yarn.lock
This PR depends on https://github.com/pagopa/io-functions-commons/pull/289
Add `rejection_detail` to `MessageStatus` when status is `REJECTED`. 
RFC 9012 - We need to distinguish the reason of a rejected message. A message can be rejected because recipient is not a user of IO, or because the service is not allowed to contact that user.
Unit tests, integration tests
> [ICC-195]  Update `function-commons` and populate `rejection_status`

- __integrations__/index.test.ts
- __integrations__/package.json
- __integrations__/yarn.lock
- __mocks__/mocks.ts
- package.json
- yarn.lock
* [Update `io-functions-commons` to `26.0.0`](9cd426294a531483aed12578dd36317fb7b8b66c);
* [Fix unit test;](c6d420ce17812ee8da46e7d4d8ccff869b34f6e8)
In order to use the `ttl` logic we want to update `io-functions-commons`.
Unit test
> [ICC-257] Update io-functions-commons to the latest version

- ProcessMessage/handler.ts
Add an event on app insight if the update ttl for all message status version of a not-user-found message update zero documents.
add event on Message process function
> Add event when update ttl return zero records

- ProcessMessage/handler.ts
- __mocks__/mocks.ts
- package.json
- yarn.lock
Add error details to app insight event generated when a cosmos error is thrown by update ttl on verisoned model
see commit history 
unit test
> Add error details to update message status ttl error

- CreateMessage/__tests__/types.test.ts
- CreateMessage/handler.ts
- CreateMessage/types.ts
- GetMessage/__tests__/handler.test.ts
- __integrations__/index.test.ts
- Add ThirdParty Support to `ApiNewMessageWithAdvancedFeatures`,
- Add unit tests
- Add Integration test
This is needed in order to provide Third Party Feature only to ADVANCED Messages.
Unit and integration tests
> [#IOCIT-153] Add premium support to Third Party Messages

- openapi/index.yaml
- openapi/index.yaml.template
Remove as contact url an unmanaged forum and replaced it with product docs reference site
Just a small user contact improvement 
n.a.
> [#IOPAE-75] OpenAPI update url field

- CreateService/__tests__/handler.test.ts
- CreateService/handler.ts
This PR add `sandbox fiscal code` if we don't pass any `authorized_recipients` inside body payload or add it to the list of `authorized_recipients`.
- [x ] Bug fix (non-breaking change which fixes an issue)
> [#IOPAE-77] Fix how handle sandboxFiscalCode

- CreateLegalMessage/__tests__/handler.test.ts
- CreateLegalMessage/impersonate.ts
- CreateService/__tests__/handler.test.ts
- CreateService/handler.ts
- EmailNotification/__tests__/handler.test.ts
- GetService/handler.ts
- GetUserServices/__tests__/handler.test.ts
- GetUserServices/handler.ts
- ProcessMessage/handler.ts
- RegenerateServiceKey/__tests__/handler.test.ts
- UpdateService/__tests__/handler.test.ts
- UpdateService/handler.ts
- UploadOrganizationLogo/__tests__/handler.test.ts
- UploadOrganizationLogo/handler.ts
- UploadServiceLogo/__tests__/handler.test.ts
- UploadServiceLogo/handler.ts
- WebhookNotification/__tests__/handler.test.ts
- __integrations__/__mocks__/CreateLegalMessage/impersonate.ts
- clients/admin.ts
- package.json
- utils/__tests__/profile.test.ts
- utils/profile.ts
- yarn.lock
* change reference to endpoint for subscriptions list
* refactor: use sdk instead of generated code
We're going to have separated operations in upstream service fn-admin
> [#IOPAE-87] change reference

- CreateService/__tests__/handler.test.ts
- GetUserServices/__tests__/handler.test.ts
- GetUserServices/handler.ts
- UpdateService/__tests__/handler.test.ts
- package.json
- yarn.lock
* update package `@pagopa/io-functions-admin-sdk`
Use latest API specification
> [#IOPSC-118] Update sdk 

- WebhookNotification/client.ts
- WebhookNotification/handler.ts
- package.json
- yarn.lock
1. imported io-backend-notifications package
2. removed script that generated definition from specification
3. switched to package sdk
to speed up build time
> use reference to package SDK

- .devops/code-review-pipelines.yml
- .github/workflows/pr-title-linter-and-linker.yaml
- Dangerfile.ts
- __integrations__/index.test.ts
- package.json
- yarn.lock
* [remove danger from pipeline](https://github.com/pagopa/io-functions-services/commit/4c34f1935e2b2d25b55140ca00b94d29231a95f0);
* [add github action for pr title and linker](https://github.com/pagopa/io-functions-services/commit/2a84c80640262cc090800bc7f0b6a895e76bd85f);
Dismit danger
> [#ICC-313] Remove danger

- UpdateService/handler.ts
- UploadServiceLogo/handler.ts
- package.json
- yarn.lock
Update _IUploadServiceHandler/IUploadServiceLogoHandler_  for Manage flow.
- UpdateService/UpdateServiceLogo API handlers
Added IAzureUserAttributesManage in _IUploadServiceHandler/IUploadServiceLogoHandler_ **attr** parameter.
> [#IOPAE-169] Update IUploadServiceHandler/IUploadServiceLogoHandler for Manage flow

- openapi/index.yaml
- openapi/index.yaml.template
This PR update section about how to get and use `Primary and Secondary Key`.
> [#IOPAE-149] Fix section about api key

- CreateMessage/handler.ts
- CreateNotification/handler.ts
* [Reduce the amount of data in some verbose logs](https://github.com/pagopa/io-functions-services/commit/1684458fbadd1ee5c49a03df988e4146f3a37de5);
> [#IOCOM-210] Reduce the amount of data in some verbose logs

- EmailNotification/__tests__/handler.test.ts
- EmailNotification/handler.ts
- EmailNotification/utils.ts
- package.json
- template_reduced_script.ts
- utils/config.ts
Add a new template mail
We need a new template mail to be used from PN
> [#IOCOM-332] Add new template mail

- package.json
The new version of the template for the mail is needed
> [#IOCOM-332] Update template version

- EmailNotification/__tests__/handler.test.ts
- EmailNotification/utils.ts
> [#IOCOM-537] Fix template mail

- openapi/index.yaml
- package.json
- yarn.lock
* [Update @pagopa/io-functions-commons to the latest version](https://github.com/pagopa/io-functions-services/commit/15af0b5773a69a3d036a1268234011312d18a05d);
* [Regenerate openapi in order to add the has_precondition field](https://github.com/pagopa/io-functions-services/commit/536ed32a8600b6a172b976a1c52ce38256d5f308);
When a `CreateMessage` is called we want to receive the parameter `has_precondition` as a partial.
> [#IIOCOM-561] Update fn commons

- openapi/index.yaml
- package.json
- yarn.lock
- [updated io-functions-commons version](https://github.com/pagopa/io-functions-services/commit/358640ad8c3dd2b1e14fcb9088731d471ee41ee1)
> [#IOCOM-370] updated io-functions-commons version

- openapi/index.yaml
- openapi/index.yaml.template
there is a typo in the open api that says that you can call the cms `retrieveService` with the service key and that is not true plus the `updateService` can return a `409 error` for no transition matched when you call `updateService` on a submitted service
> [#IOPAE-710] Fix Get and Update service cms openAPI

- __integrations__/index.test.ts
- openapi/index.yaml
- package.json
- yarn.lock
* [Update io-functions-commons to add the flag has_remote_content](https://github.com/pagopa/io-functions-services/commit/05733a65c325bec7358b77d2901ac9c53a348875);
* [Regenerage opanapi spec](https://github.com/pagopa/io-functions-services/commit/d74c0859119ee6f92ad1b0001288fd5d1f09ea05);
The caller of the CreateMessage needs to tell us if the massage contains remote content.
> [#IOCOM-704] Add has_remote_content flag

- openapi/index.yaml
- openapi/index.yaml.template
- package.json
Add service topic to OpenAPI
- add new services/topics endpoint
- add topic_id property to request payload
- add topic object to response
> [IOPAE-687] add service topic to OpenAPI

- openapi/index.yaml
- openapi/index.yaml.template
> [IOPAE-687] update /manage/services/topics API summary

- __integrations__/__mocks__/server/io-functions-service-messages.mock.ts
- package.json
> Fix generate api script

- openapi/index.yaml
- openapi/index.yaml.template
> [IOCOM-2180] Make content non mandatory in Get Message response openapi

- EmailNotification/__tests__/__snapshots__/utils.test.ts.snap
- EmailNotification/__tests__/handler.test.ts
- EmailNotification/utils.ts
- package.json
- yarn.lock
- Removed the old script for generating email template
- Add the new dependency `@pagopa/io-app-email-templates` with the new MessagePreview template
- Use the new template when sending the email for the new message
> [#IOCOM-2229] Use new email template for EmailNotification

- EmailNotification/__tests__/__snapshots__/utils.test.ts.snap
- package.json
- yarn.lock
Update the  @pagopa/io-app-email-templates package.
Update tests
Tested running yarn test locally. Used yarn test -u to updated snippet.
> [IOCOM-2321] Update message preview UTM url

- openapi/index.yaml
- openapi/index.yaml.template
- package.json
- yarn.lock
- update `io-functions-commons` dependency
- deprecate `token_name` field
> [IOPAE-2091] OpenAPI: deprecate token_name field
