GetLimitedProfile/__tests__/handler.test.ts, GetLimitedProfile/function.json, GetLimitedProfile/handler.ts, GetLimitedProfile/index.ts, jest.config.js, utils/arbitraries.ts
Draft because we need to decide how to handle the routes of the two http triggered functions.
For GetLimitedProfile i have set `v1/profiles/{fiscalCode}`. If it is ok for you i can change the CreateMessage route from `{*segments}` to `v1/messages/{fiscalCode}`.
=> [#167569704] Add GetLimitedProfile function

openapi/index.yaml
=> [#168694799] Update specification for CreateMessage

CreateNotificationActivity/handler.ts
Since not every user profile stored into CosmosDB has email flags defined (so they are neither true nor false), we use strict equality and assume `isEmailEnabled = true` and `isEmailValidated = true` when they're undefined.
=> [#169703944] check isEmailValidated / isEmailEnabled flags before sending email

CreatedMessageOrchestrator/index.ts, WebhookNotificationActivity/__tests__/handler.test.ts, WebhookNotificationActivity/client.ts, WebhookNotificationActivity/handler.ts, WebhookNotificationActivity/index.ts, package.json, tslint.json, yarn.lock
drop superagent and use node-fetch with timeout and keepalive to call the notify webhook
=> [#172163927] add keepalive and timeout to webhook calls

CreateMessage/handler.ts, CreateMessage/index.ts, EmailNotificationActivity/handler.ts, WebhookNotificationActivity/__tests__/handler.test.ts, WebhookNotificationActivity/handler.ts, WebhookNotificationActivity/index.ts, package.json, yarn.lock
- removed tracking of dependency since they are now auto-tracked by default
- pass the correct operationId to correlate custom event to parent call
=> [#172201213] refactor application insights tracking

CreateNotificationActivity/__tests__/utils.test.ts, CreateNotificationActivity/handler.ts, CreateNotificationActivity/index.ts, CreateNotificationActivity/utils.ts
Added `EMAIL_NOTIFICATION_SERVICE_BLACKLIST` to add a list of services for which we don't send email, no matter what. The var is optional, default is: **no service is blacklisted**.
```sh
EMAIL_NOTIFICATION_SERVICE_BLACKLIST=xxx
EMAIL_NOTIFICATION_SERVICE_BLACKLIST=xxx,yyy
```
=> [#173608840] Add email blacklist for configured services

GetLimitedProfile/__tests__/handler.test.ts, GetLimitedProfile/handler.ts, GetLimitedProfileByPOST/__tests__/handler.test.ts, GetLimitedProfileByPOST/handler.ts, utils/arbitraries.ts
User profiles with isInboxEnabled=false must be treated as not existing.
=> [#174727933] Check isInboxEnabled before returning the user profile

CreateService/handler.ts, GetService/handler.ts, GetUserServices/handler.ts, RegenerateServiceKey/handler.ts, UpdateService/handler.ts, UploadServiceLogo/handler.ts, utils/api.ts
This PR includes a new utility function `withApiRequestWrapper` that allows to wrap API calls and generalize a common pattern described [here](https://github.com/pagopa/io-functions-services/pull/75#discussion_r490971555).
=> [#174902061] Refactoring Api call tasks

openapi/index.yaml, package.json, utils/arbitraries.ts, yarn.lock
This PR is intended to avoid generated api clients to use `Bearer` token authentication while calling io-functions-admin APIs
=> [#175185887] Upgrade Italia-utils to allow Api auth without bearer

GetSubscriptionsFeed/__tests__/handler.test.ts, GetSubscriptionsFeed/handler.ts
This PR adds retrieve for records with partitionKey`P-{date}-U` on `SubscriptionFeedByDay` while serving informations about subscription feed. These kind of records are written, when users request to delete its own data and in that case, the event must be notified to subscription feed.
=> [#175497433] Add Profile unsubscription on feed

Info/__tests__/handler.test.ts, Info/handler.ts, utils/healthcheck.ts
This PR introduces the health check in info endpoint,
that check for wrong configuration and unreachable resources (cosmosdb, storage, urls)
=> [#175119536] Add health check

package.json, yarn.lock
This PR bumps io-functions-commons to latest version, in order to enable last email's template usage, due to old logo's path.
=> [#176117044] Upgrade email template by bumping io-fn-commons

CreateMessage/__tests__/handler.test.ts, CreateMessage/handler.ts, CreateMessage/index.ts, GetLimitedProfile/__tests__/handler.test.ts, GetLimitedProfile/handler.ts, GetLimitedProfile/index.ts, GetLimitedProfileByPOST/__tests__/handler.test.ts, GetLimitedProfileByPOST/handler.ts, GetLimitedProfileByPOST/index.ts, GetMessage/__tests__/handler.test.ts, GetSubscriptionsFeed/__tests__/handler.test.ts, GetSubscriptionsFeed/handler.ts, GetSubscriptionsFeed/index.ts, __mocks__/durable-functions.ts, __mocks__/mocks.ts, package.json, tsconfig.json, utils/config.ts, utils/profile.ts, yarn.lock
If the feature flag `FF_DISABLE_INCOMPLETE_SERVICES` is `true` only services matching that `ValidService` type can use:
- CreateMessage
- GetLimitedProfile
- GetLimitedProfileByPOST
- GetSubscriptionFeed
Some Services added into `FF_INCOMPLETE_SERVICE_WHITELIST` can bypass `ValidService` check.
A Services that haven't the required metadata information can't be enabled to use some API. We need to specify through the feature flag when this filtering is enabled and a whitelist of services that don't need this check.
unit test
test with `io-mock`
=> [#ENTE-82] Limit API access for incomplete services

openapi/index.yaml, openapi/index.yaml.template
Several APIs are exposed without explicitly declaring a 403 can happen, although they actually do. Mostly, this status can happen when the DevPortal user doesn't belong to the group allowed for such operaration.
Operations are: 
- `submitMessageforUserWithFiscalCodeInBody`
- `submitMessageforUser`
- `getMessage`
- `getProfileByPOST`
- `getProfile`
- `getSubscriptionsFeedForDate`
- `createService`
- `getUserServices`
=> [#IP-210] Add 403 to API specs where missing

CreateMessage/__tests__/handler.test.ts, CreateMessage/__tests__/types.test.ts, CreateMessage/handler.ts, CreateMessage/types.ts, openapi/index.yaml, package.json, yarn.lock
Update message model to allow `eu_covid_cert` in the content payload. Such field must be allowed only for users belonging to `ApiMessageWriteEUCovidCert` group.
TODO: implement https://github.com/pagopa/io-functions-commons/pull/167 when ready
=> [#IP-215] Allow `eu_covid_cert` in message content

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml
* edit deploy pipeline to allow parallel deploy on multiple app services
* update pipelines templates
We may need to increase batch job parallelism. As they are built using Azure Durable Functions, and as they have an upper bound of maximum number of Orchestrators running at the same time, to increase such value we must deploy on different app services at once.
So far, the deploy pipeline still has a default of one app service (the one actually deployed). We may change this value in the future, still we can provide different inputs before running the pipeline.
=> [#IPV-22] Enable deploy on multiple app services

WebhookNotificationActivity/__tests__/handler.test.ts, WebhookNotificationActivity/handler.ts, WebhookNotificationActivity/index.ts, utils/config.ts
- Add new feature flag `FF_DISABLE_WEBHOOK_MESSAGE_CONTENT` in configuration (default `false`)
- With `FF_DISABLE_WEBHOOK_MESSAGE_CONTENT` enabled all the webhook message content will be disabled
We want send push notifications with a generic payload and title. With `FF_DISABLE_WEBHOOK_MESSAGE_CONTENT` enabled we remove content from the webhook message, and `io-backend` provide a generic one.
unit test
=> [#IP-234] Disable message content for WEBHOOK channel

CreateNotificationActivity/handler.ts, EmailNotificationActivity/__tests__/handler.test.ts, GetSubscriptionsFeed/__tests__/handler.test.ts, StoreMessageContentActivity/__tests__/handler.test.ts, StoreMessageContentActivity/handler.ts, StoreMessageContentActivity/index.ts, __mocks__/mocks.ts, package.json, utils/__tests__/arbitraries.ts, utils/config.ts, yarn.lock
- Add `EMAIL_MODE_SWITCH_LIMIT_DATE` env property
- Update `StoreMessageContentActivity` in order to override `isEmailEnabled` based on profile' s timestamp check
- Upgrade `io-functions-commons` version
- Add unit test on `StoreMessageContentActivity`
- Tests refactor related to `io-functions-commons` upgrade
We want that an organization can't reach on email channel a citizen with an old profile, or even if his profile has not been recently upserted (after `EMAIL_MODE_SWITCH_LIMIT_DATE`)
=> [#IP-292] Add override on isEmailEnabled value for old profiles

package.json, utils/config.ts, yarn.lock
In order to make Date env variable compliant to App service issue we must to parse Date with Timestamp format
- Move `OPT_OUT_EMAIL_SWITCH_DATE` format to Timestamp
- Upgrade `@pagopa/ts-commons` package
This PR allows us to use Timestamp format on Date env variable
Unit test
=> [#IP-297] Move OPT_OUT_EMAIL_SWITCH_DATE to Timestamp format

StoreMessageContentActivity/__tests__/handler.test.ts, StoreMessageContentActivity/handler.ts, StoreMessageContentActivity/index.ts, utils/config.ts
In order to enable opt in email we need a Feature flag that could drive our beta phase without impacting default behaviour before the release date.
- Add `FF_OPT_IN_EMAIL_ENABLED` env variable
- Update `StoreMessageContentActivity`
- Add Unit test based on new env variable
This PR allows us to enable opt in email at the right moment
Unit test
=> Add FF_OPT_IN_EMAIL_ENABLED Feature Flag

CreateNotificationActivity/handler.ts
User that using App version `1.29.0.1` can receive email if email is enabled in user profile.
`CreateNotificationActivity` evaluate service level email preference for profiles with preferences mode `AUTO` or `MANUAL` always enabled.
User of App version `1.29.0.1` cannot change email service preferences. Only profile level email preferences should works.
not tested
=> [#IP-300] Temporary ignore email service preference for not Legacy profiles

GetSubscriptionsFeed/__tests__/handler.test.ts, GetSubscriptionsFeed/handler.ts
User that enables a single service after switching to MANUAL mode, must be tracked on Subscription Feed because Profile Unsubscription is not related only to a Profile deletion.
- `GetSubscriptioFeed` evaluate service subscription while it reads a profile unsubscription
- Update test
It solves a data inconsistence if User enables a single service after switching to MANUAL mode in the same day.
Unit tested
=> [#IP-301] `GetSubscriptionFeed` Add service subscription check on profile unsubscription

StoreMessageContentActivity/__tests__/handler.test.ts, StoreMessageContentActivity/handler.ts, StoreMessageContentActivity/index.ts, utils/__tests__/profile.test.ts, utils/crypto.ts
Add the `api.messages.create.blockedstoremessage` custom event so that we can monitor:
* how many messages are accepted/rejected due to Citizen preferences
* how many Citizens are receiving messages and are in `LEGACY` mode
* how many messages are rejected, grouped by preference mode
=> [#IP-303] Add tracing for message storing

CreateNotificationActivity/handler.ts
When the message is sent to the SANDBOX_FISCAL_CODE the email address (overridden with the sender email address) is considered enabled and validated.
A developer that was testing the `CreateMessage` API doesn't receive the email for validating his implementation.
not tested
=> [#ENTE-130] Messages to SANDBOX account don't send emails to services user

GetMessage/index.ts, GetSubscriptionsFeed/index.ts, Info/handler.ts, ProcessMessage/index.ts, StoreMessageContentActivity/index.ts, utils/config.ts
Refactor storage configuration so we can have clear distinction of storages depending on their usages:
=> Refactor storage configuration

CreateMessage/handler.ts, CreateService/__tests__/handler.test.ts, CreateService/handler.ts, EmailNotification/__tests__/handler.test.ts, ProcessMessage/__tests__/handler.test.ts, ProcessMessage/handler.ts, ProcessMessage/index.ts, UpdateService/__tests__/handler.test.ts, UpdateService/handler.ts, WebhookNotification/__tests__/handler.test.ts, __mocks__/mocks.ts, openapi/index.yaml, openapi/index.yaml.template, package.json, yarn.lock
Upgrade `io-functions-commons` dependency for SpecialServices
CreateMessage flow now have `serviceCategory` to handle Standard and Special service preferences check.
Only admin can create and edit `SpecialService` properties.
The `io-functions-services` should handle Standard and Special services. This PR upgrade specifications and models to do that.
When a message is created for a Special Service to evaluate if INBOX is enabled for a User, Activation model is used to retrieve Special Service activation.
unit test
=> [#IC-49] Porting SpecialServices to new ProcessMessage flow

CreateLegalMessage/__tests__/handler.test.ts, CreateLegalMessage/handler.ts, openapi/index.yaml, package.json, yarn.lock
The Legal Message could be sent to IO by different PEC-SERVER. IO must store the PEC-SERVER sender ID in order to properly manage message nerichment.
add pec-server service enrichment to legal_data in the CreateLegalMessage function
Properly store the pec-server id of the legal message sender without relying on external input
Unit test
=> [#IC-206] Enable multi-provider for Legal Message

OnFailedProcessMessage/__tests__/handler.test.ts, OnFailedProcessMessage/handler.ts, OnFailedProcessMessage/index.ts, ProcessMessage/__tests__/handler.test.ts, ProcessMessage/handler.ts, __mocks__/mocks.ts, package.json, yarn.lock
Currently, the _message_status_ collection do not contain the message owner _fiscalCode_. This will reduce the performace of querying the message from its status (with _messageId_ alone, the query on _messages_ collection is 8 times more RU consuming).
add fiscalCode on create message process
add fiscalCode on failed process
We need to retrieve the message from its status in order to keep aligned the view used by paginated list messages and search messages operations.
unit tests
=> [#IC-349]  Add fiscalCode to message_status in CreateMessage process

CreateMessage/handler.ts, GetMessage/__tests__/handler.test.ts, GetMessage/handler.ts, __integrations__/index.test.ts, docker/fixtures/src/data/data.ts, package.json, yarn.lock
* Updated `ts-commons` to `10.9.0`
* Updated `io-function-commons` to `25.6.2`
* Updated some error messages to be clearer
* Added some integration tests
* Added some unit tests
In order to have more self explanatory error messages i have updated some detail
unit and integration test
=> [ICC-168] more self explanatory error messages

CreateService/handler.ts
* add `has_primary_key` and `has_secondary_key` attribute on `api.services.create` tracing event
`
We have feedback of Services created correctly but the payload does not contain the ApiKey. This PR introduces a traces so that we can have evidence of the bug
=> [#IOPSC-81] Trace ApiKey existence on Service creation

OnFailedProcessMessage/__tests__/handler.test.ts, ProcessMessage/__tests__/handler.test.ts, ProcessMessage/handler.ts, package.json, yarn.lock
* Update `@pagopa/io-functions-commons`;
* Set the `ttl` during the upsert when the user does not exist;
We need to set the ttl directly when creating the entry of the message status in order to solve an issue with cosmos.
Unit test
=> [IOCIT-195] Use messageStatusUpdarter to set the ttl

CreateService/__tests__/handler.test.ts, CreateService/handler.ts
Added the possibility to use **MANAGE** Subscription API Key as `Ocp-Apim-Subscription-Key` in CreateService API.
In this way we are introducing the concept of MANAGE Flow for Service Management APIs.
Update **CreateService** with the possibility to use the **MANAGE** Subscription API Key
Reduce User Errors with a restricted API Key scope.
Unit Test
=> [#IOPAE-174]add possibility to create service with manage key

RegenerateServiceKey/__tests__/handler.test.ts, RegenerateServiceKey/handler.ts
Added the possibility to use _MANAGE Subscription API Key_ as `Ocp-Apim-Subscription-Key` in **RegenerateServiceKey** API.
In this way we are introducing the concept of _MANAGE Flow_ for Service Management APIs.
- Update *RegenerateServiceKey* with the possibility to use the _MANAGE Subscription API Key_
- Related Unit Tests
Reduce User Errors with a restricted API Key scope, especially in case of Service Keys Update.
Unit Tests
=> [#IOPAE-175] Update RegenerateServiceKey with Manage Flow

CreateMessage/__tests__/handler.test.ts, CreateMessage/handler.ts, utils/__tests__/arbitraries.ts
Removed the `default_addresses` field from user input when creating a message
The field has been deprecated long ago and it's no longer used by our users. We can safely remove it as it's an operational value that does not affect the stored message.
=> [IOPAE-218] remove `default_addresses`

openapi/index.yaml, openapi/index.yaml.template
Update openapi for cms services
- update openapi security definitions (distinguish between manage and use apikey)
- remove cmsExplainService operation (not implemented yet)
Making openapi definition cleaner
=> [IOPAE-406] update openapi for cms services

EmailNotification/__tests__/__snapshots__/utils.test.ts.snap, EmailNotification/__tests__/handler.test.ts, EmailNotification/__tests__/utils.test.ts, EmailNotification/utils.ts
[Add "..." at the end of the message content when it's truncated](https://github.com/pagopa/io-functions-services/commit/fab54b6ef33c75c3951cd5f30a4f9e91806b6b85)
unit test
=> [#IOCOM-538] Add "..." at the end of the message content when it's truncated

CreateMessage/__tests__/handler.test.ts, CreateMessage/handler.ts
* [Return 403 if attachments are provided with a non premium message](https://github.com/pagopa/io-functions-services/commit/e9a9bc5edbc9dfdaa4f880c3faa270abcf5b7064)
We want to open the possibility to send `third_party_data` to all the services in order to open the remote content.
On the other hand attachments should be available only for premium messages.
unit test.
=> [#IOCOM-705] Return 403 if attachments are provided with a non premium message

openapi/index.yaml, openapi/index.yaml.template
the version field does not exist in services cms , the service cms api do not return version on response
- remove version field from services cms api and documentation
=> [IOPAE-808]bugfix: remove version from cms api response and documentation

EmailNotification/__tests__/utils.test.ts, EmailNotification/utils.ts
* [Remove links from the text in email](https://github.com/pagopa/io-functions-services/commit/aac099ef84078d9119e0061906b9897d912de7c7);
We want to avoid links when sending an email
Unit test
=> [IOCOM-888] Remove links from the text in email

CreateMessage/__tests__/handler.test.ts, openapi/index.yaml, package.json, yarn.lock
- [new io-functions-commons version for configuration_id fiel in CreateM…](https://github.com/pagopa/io-functions-services/pull/296/commits/d19dcf97e7a513b54ab8537c0829248ec732c2e8)
Updated the io-functions-commons version in order to add the new optional configuration_id field in the CreateMessage API
=> [#IOCOM-920] new io-functions-commons version for configuration_id field in CreateMessage

openapi/index.yaml, openapi/index.yaml.template, package.json, yarn.lock
Moved security header to every path because.
Codegen does not allow the override for just CMS endpoints, so we have to move security headers to every endpoint.
yarn build
codegen client
tests
=> [#IOCOM-1005] Fixed openapi with endpoint placed security

EmailNotification/__tests__/__snapshots__/utils.test.ts.snap, EmailNotification/__tests__/handler.test.ts, EmailNotification/__tests__/utils.test.ts, EmailNotification/utils.ts
* [Replace links with a warning](https://github.com/pagopa/io-functions-services/commit/eaad9b401b2cd2928d3d462a111831d3b8e56fe2);
* [Invalidate clickable links](https://github.com/pagopa/io-functions-services/commit/c17647a887e0864be89a936397ff2bb746af22cc);
The text where we are using the regex will always been of 134 character so we are not affected by the problem highlighted by sonar.
We want to avoid clickable links in email
Unit test
=> [#IOCOM-987] Invalidate clickable links in email

openapi/index.yaml, openapi/index.yaml.template
Add ServiceHistory Manage API, Topic_Id is now mandatory on manage create and manage update service
- Add `GET /manage/services/{serviceId}/history` API
- `topic_id` field is now mandatory on Json Body for `PUT /manage/services/{serviceId}` and `POST /manage/services` APIs
=> [#IOPAE-1053] ServiceHistory Manage API and mandatory Topic_Id

__integrations__/__mocks__/server/io-functions-service-messages.mock.ts, openapi/index.yaml, openapi/index.yaml.template, package.json
Added remote content manage APIs and definitions.
We need to expose these new APIs on the public guide.
=> [IOCOM-1313] feat(openapi): Added remote content manage api

GetMessage/userPreferenceChecker/__tests__/messageReadStatusAuth.test.ts, GetMessage/userPreferenceChecker/__tests__/userPreferencesCheckerFactory.test.ts, GetMessage/userPreferenceChecker/userPreferencesCheckerFactory.ts
Added check to manage LEGACY user service preference as UNKNOWN like if we do not know the user's app version.
We need to manage users with LEGACY service preferences because actually they were not considered to exists.
- build
- unit test
- lint
=> [#IOCOM-1597] Managed LEGACY user as app UNKNOWN
